image: "python:3.7"

stages:
  - deploy
  - deploy_after

before_script:
   - pip install wheel
   - pip install twine
   - python setup.py bdist_wheel

deploy_private:
  stage: deploy
  script:
    - twine upload --username hongkang2 --password He8JGUiK dist/* --repository-url http://52.81.42.99:31187/
  only:
    - tagsdeploy_after:
  stage: deploy_after
  script:
    - echo ${CI_RUNNER_TAGS} 
    - pip install spider_layer==${CI_RUNNER_TAGS} -i http://52.81.42.99:31187/simple --trusted-host 52.81.42.99 -t ./python
  only:
    - tags