# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import device_pb2 as device__pb2
from . import ping_pb2 as ping__pb2
from . import user_pb2 as user__pb2


class MirrorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/mirror.Mirror/Ping',
                request_serializer=ping__pb2.PingRequest.SerializeToString,
                response_deserializer=ping__pb2.PingResponse.FromString,
                )
        self.GetUserList = channel.unary_unary(
                '/mirror.Mirror/GetUserList',
                request_serializer=user__pb2.GetUserListRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserListResponse.FromString,
                )
        self.GetDevicesByPartnerUser = channel.unary_unary(
                '/mirror.Mirror/GetDevicesByPartnerUser',
                request_serializer=device__pb2.GetDevicesByPartnerUserRequest.SerializeToString,
                response_deserializer=device__pb2.GetDevicesByPartnerUserResponse.FromString,
                )
        self.GetPartnerDevicesByIds = channel.unary_unary(
                '/mirror.Mirror/GetPartnerDevicesByIds',
                request_serializer=device__pb2.GetPartnerDevicesByIdsRequest.SerializeToString,
                response_deserializer=device__pb2.GetPartnerDevicesByIdsResponse.FromString,
                )
        self.GetUsersRange = channel.unary_unary(
                '/mirror.Mirror/GetUsersRange',
                request_serializer=user__pb2.GetUsersRangeRequest.SerializeToString,
                response_deserializer=user__pb2.GetUsersRangeResponse.FromString,
                )
        self.GetDevicesRange = channel.unary_unary(
                '/mirror.Mirror/GetDevicesRange',
                request_serializer=device__pb2.GetDevicesRangeRequest.SerializeToString,
                response_deserializer=device__pb2.GetDevicesRangeResponse.FromString,
                )
        self.GetUserDevicesRange = channel.unary_unary(
                '/mirror.Mirror/GetUserDevicesRange',
                request_serializer=device__pb2.GetUserDevicesRangeRequest.SerializeToString,
                response_deserializer=device__pb2.GetUserDevicesRangeResponse.FromString,
                )


class MirrorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserList(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevicesByPartnerUser(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartnerDevicesByIds(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersRange(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDevicesRange(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDevicesRange(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MirrorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=ping__pb2.PingRequest.FromString,
                    response_serializer=ping__pb2.PingResponse.SerializeToString,
            ),
            'GetUserList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserList,
                    request_deserializer=user__pb2.GetUserListRequest.FromString,
                    response_serializer=user__pb2.GetUserListResponse.SerializeToString,
            ),
            'GetDevicesByPartnerUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevicesByPartnerUser,
                    request_deserializer=device__pb2.GetDevicesByPartnerUserRequest.FromString,
                    response_serializer=device__pb2.GetDevicesByPartnerUserResponse.SerializeToString,
            ),
            'GetPartnerDevicesByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartnerDevicesByIds,
                    request_deserializer=device__pb2.GetPartnerDevicesByIdsRequest.FromString,
                    response_serializer=device__pb2.GetPartnerDevicesByIdsResponse.SerializeToString,
            ),
            'GetUsersRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersRange,
                    request_deserializer=user__pb2.GetUsersRangeRequest.FromString,
                    response_serializer=user__pb2.GetUsersRangeResponse.SerializeToString,
            ),
            'GetDevicesRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDevicesRange,
                    request_deserializer=device__pb2.GetDevicesRangeRequest.FromString,
                    response_serializer=device__pb2.GetDevicesRangeResponse.SerializeToString,
            ),
            'GetUserDevicesRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDevicesRange,
                    request_deserializer=device__pb2.GetUserDevicesRangeRequest.FromString,
                    response_serializer=device__pb2.GetUserDevicesRangeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mirror.Mirror', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mirror(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mirror.Mirror/Ping',
            ping__pb2.PingRequest.SerializeToString,
            ping__pb2.PingResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mirror.Mirror/GetUserList',
            user__pb2.GetUserListRequest.SerializeToString,
            user__pb2.GetUserListResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevicesByPartnerUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mirror.Mirror/GetDevicesByPartnerUser',
            device__pb2.GetDevicesByPartnerUserRequest.SerializeToString,
            device__pb2.GetDevicesByPartnerUserResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPartnerDevicesByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mirror.Mirror/GetPartnerDevicesByIds',
            device__pb2.GetPartnerDevicesByIdsRequest.SerializeToString,
            device__pb2.GetPartnerDevicesByIdsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsersRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mirror.Mirror/GetUsersRange',
            user__pb2.GetUsersRangeRequest.SerializeToString,
            user__pb2.GetUsersRangeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDevicesRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mirror.Mirror/GetDevicesRange',
            device__pb2.GetDevicesRangeRequest.SerializeToString,
            device__pb2.GetDevicesRangeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserDevicesRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mirror.Mirror/GetUserDevicesRange',
            device__pb2.GetUserDevicesRangeRequest.SerializeToString,
            device__pb2.GetUserDevicesRangeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
