# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mirror_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from . import ping_pb2 as ping__pb2
from . import user_pb2 as user__pb2
from . import device_pb2 as device__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mirror_service.proto',
  package='mirror',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14mirror_service.proto\x12\x06mirror\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\nping.proto\x1a\nuser.proto\x1a\x0c\x64\x65vice.proto2\xaf\x07\n\x06Mirror\x12G\n\x04Ping\x12\x13.mirror.PingRequest\x1a\x14.mirror.PingResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/mirror/ping\x12]\n\x0bGetUserList\x12\x1a.mirror.GetUserListRequest\x1a\x1b.mirror.GetUserListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/mirror/users\x12\xb1\x01\n\x17GetDevicesByPartnerUser\x12&.mirror.GetDevicesByPartnerUserRequest\x1a\'.mirror.GetDevicesByPartnerUserResponse\"E\x82\xd3\xe4\x93\x02?\x12=/mirror/partner/{partner_uuid}/user/{partner_user_id}/devices\x12\x9e\x01\n\x16GetPartnerDevicesByIds\x12%.mirror.GetPartnerDevicesByIdsRequest\x1a&.mirror.GetPartnerDevicesByIdsResponse\"5\x82\xd3\xe4\x93\x02/\x12-/mirror/partner/{partner_uuid}/devices_by_ids\x12\x80\x01\n\rGetUsersRange\x12\x1c.mirror.GetUsersRangeRequest\x1a\x1d.mirror.GetUsersRangeResponse\"2\x82\xd3\xe4\x93\x02,\x12*/mirror/partner/{partner_uuid}/users_range\x12\x88\x01\n\x0fGetDevicesRange\x12\x1e.mirror.GetDevicesRangeRequest\x1a\x1f.mirror.GetDevicesRangeResponse\"4\x82\xd3\xe4\x93\x02.\x12,/mirror/partner/{partner_uuid}/devices_range\x12\x99\x01\n\x13GetUserDevicesRange\x12\".mirror.GetUserDevicesRangeRequest\x1a#.mirror.GetUserDevicesRangeResponse\"9\x82\xd3\xe4\x93\x02\x33\x12\x31/mirror/partner/{partner_uuid}/user_devices_rangeb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,ping__pb2.DESCRIPTOR,user__pb2.DESCRIPTOR,device__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MIRROR = _descriptor.ServiceDescriptor(
  name='Mirror',
  full_name='mirror.Mirror',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=128,
  serialized_end=1071,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='mirror.Mirror.Ping',
    index=0,
    containing_service=None,
    input_type=ping__pb2._PINGREQUEST,
    output_type=ping__pb2._PINGRESPONSE,
    serialized_options=b'\202\323\344\223\002\016\022\014/mirror/ping',
  ),
  _descriptor.MethodDescriptor(
    name='GetUserList',
    full_name='mirror.Mirror.GetUserList',
    index=1,
    containing_service=None,
    input_type=user__pb2._GETUSERLISTREQUEST,
    output_type=user__pb2._GETUSERLISTRESPONSE,
    serialized_options=b'\202\323\344\223\002\017\022\r/mirror/users',
  ),
  _descriptor.MethodDescriptor(
    name='GetDevicesByPartnerUser',
    full_name='mirror.Mirror.GetDevicesByPartnerUser',
    index=2,
    containing_service=None,
    input_type=device__pb2._GETDEVICESBYPARTNERUSERREQUEST,
    output_type=device__pb2._GETDEVICESBYPARTNERUSERRESPONSE,
    serialized_options=b'\202\323\344\223\002?\022=/mirror/partner/{partner_uuid}/user/{partner_user_id}/devices',
  ),
  _descriptor.MethodDescriptor(
    name='GetPartnerDevicesByIds',
    full_name='mirror.Mirror.GetPartnerDevicesByIds',
    index=3,
    containing_service=None,
    input_type=device__pb2._GETPARTNERDEVICESBYIDSREQUEST,
    output_type=device__pb2._GETPARTNERDEVICESBYIDSRESPONSE,
    serialized_options=b'\202\323\344\223\002/\022-/mirror/partner/{partner_uuid}/devices_by_ids',
  ),
  _descriptor.MethodDescriptor(
    name='GetUsersRange',
    full_name='mirror.Mirror.GetUsersRange',
    index=4,
    containing_service=None,
    input_type=user__pb2._GETUSERSRANGEREQUEST,
    output_type=user__pb2._GETUSERSRANGERESPONSE,
    serialized_options=b'\202\323\344\223\002,\022*/mirror/partner/{partner_uuid}/users_range',
  ),
  _descriptor.MethodDescriptor(
    name='GetDevicesRange',
    full_name='mirror.Mirror.GetDevicesRange',
    index=5,
    containing_service=None,
    input_type=device__pb2._GETDEVICESRANGEREQUEST,
    output_type=device__pb2._GETDEVICESRANGERESPONSE,
    serialized_options=b'\202\323\344\223\002.\022,/mirror/partner/{partner_uuid}/devices_range',
  ),
  _descriptor.MethodDescriptor(
    name='GetUserDevicesRange',
    full_name='mirror.Mirror.GetUserDevicesRange',
    index=6,
    containing_service=None,
    input_type=device__pb2._GETUSERDEVICESRANGEREQUEST,
    output_type=device__pb2._GETUSERDEVICESRANGERESPONSE,
    serialized_options=b'\202\323\344\223\0023\0221/mirror/partner/{partner_uuid}/user_devices_range',
  ),
])
_sym_db.RegisterServiceDescriptor(_MIRROR)

DESCRIPTOR.services_by_name['Mirror'] = _MIRROR

# @@protoc_insertion_point(module_scope)
