# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='mirror',
  syntax='proto3',
  serialized_options=b'\n(com.tcl.cloud.proto.partnermirror.mirror',
  serialized_pb=b'\n\nuser.proto\x12\x06mirror\"\xd6\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cpartner_name\x18\x02 \x01(\t\x12\x14\n\x0cpartner_uuid\x18\x03 \x01(\t\x12\x16\n\x0eorigin_user_id\x18\x04 \x01(\x05\x12\x11\n\tnick_name\x18\x05 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\x12\x14\n\x0cmobile_phone\x18\x08 \x01(\t\x12\x0c\n\x04\x62ody\x18\t \x01(\t\x12\x12\n\ncreated_at\x18\n \x01(\t\x12\x12\n\nupdated_at\x18\x0b \x01(\t\"W\n\rUsersPageData\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\x1b\n\x05users\x18\x04 \x03(\x0b\x32\x0c.mirror.User\"j\n\x12GetUserListRequest\x12\x14\n\x0cpartner_uuid\x18\x01 \x01(\t\x12\x11\n\tsearch_by\x18\x02 \x03(\t\x12\x0f\n\x07sort_by\x18\x03 \x03(\t\x12\x0c\n\x04page\x18\x04 \x01(\x05\x12\x0c\n\x04size\x18\x05 \x01(\x05\"Y\n\x13GetUserListResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x15.mirror.UsersPageData\"/\n\x11GetUsersRangeData\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\",\n\x14GetUsersRangeRequest\x12\x14\n\x0cpartner_uuid\x18\x01 \x01(\t\"_\n\x15GetUsersRangeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\'\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x19.mirror.GetUsersRangeDataB*\n(com.tcl.cloud.proto.partnermirror.mirrorb\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='mirror.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mirror.User.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partner_name', full_name='mirror.User.partner_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partner_uuid', full_name='mirror.User.partner_uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin_user_id', full_name='mirror.User.origin_user_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nick_name', full_name='mirror.User.nick_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='mirror.User.category', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='mirror.User.email', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobile_phone', full_name='mirror.User.mobile_phone', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='mirror.User.body', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='mirror.User.created_at', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='mirror.User.updated_at', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=237,
)


_USERSPAGEDATA = _descriptor.Descriptor(
  name='UsersPageData',
  full_name='mirror.UsersPageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='mirror.UsersPageData.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page', full_name='mirror.UsersPageData.page', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='mirror.UsersPageData.size', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='mirror.UsersPageData.users', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=326,
)


_GETUSERLISTREQUEST = _descriptor.Descriptor(
  name='GetUserListRequest',
  full_name='mirror.GetUserListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partner_uuid', full_name='mirror.GetUserListRequest.partner_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='search_by', full_name='mirror.GetUserListRequest.search_by', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sort_by', full_name='mirror.GetUserListRequest.sort_by', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page', full_name='mirror.GetUserListRequest.page', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='mirror.GetUserListRequest.size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=434,
)


_GETUSERLISTRESPONSE = _descriptor.Descriptor(
  name='GetUserListResponse',
  full_name='mirror.GetUserListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mirror.GetUserListResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='mirror.GetUserListResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='mirror.GetUserListResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=525,
)


_GETUSERSRANGEDATA = _descriptor.Descriptor(
  name='GetUsersRangeData',
  full_name='mirror.GetUsersRangeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='mirror.GetUsersRangeData.start', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='mirror.GetUsersRangeData.end', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=574,
)


_GETUSERSRANGEREQUEST = _descriptor.Descriptor(
  name='GetUsersRangeRequest',
  full_name='mirror.GetUsersRangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partner_uuid', full_name='mirror.GetUsersRangeRequest.partner_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=576,
  serialized_end=620,
)


_GETUSERSRANGERESPONSE = _descriptor.Descriptor(
  name='GetUsersRangeResponse',
  full_name='mirror.GetUsersRangeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mirror.GetUsersRangeResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='mirror.GetUsersRangeResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='mirror.GetUsersRangeResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=717,
)

_USERSPAGEDATA.fields_by_name['users'].message_type = _USER
_GETUSERLISTRESPONSE.fields_by_name['data'].message_type = _USERSPAGEDATA
_GETUSERSRANGERESPONSE.fields_by_name['data'].message_type = _GETUSERSRANGEDATA
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UsersPageData'] = _USERSPAGEDATA
DESCRIPTOR.message_types_by_name['GetUserListRequest'] = _GETUSERLISTREQUEST
DESCRIPTOR.message_types_by_name['GetUserListResponse'] = _GETUSERLISTRESPONSE
DESCRIPTOR.message_types_by_name['GetUsersRangeData'] = _GETUSERSRANGEDATA
DESCRIPTOR.message_types_by_name['GetUsersRangeRequest'] = _GETUSERSRANGEREQUEST
DESCRIPTOR.message_types_by_name['GetUsersRangeResponse'] = _GETUSERSRANGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:mirror.User)
  })
_sym_db.RegisterMessage(User)

UsersPageData = _reflection.GeneratedProtocolMessageType('UsersPageData', (_message.Message,), {
  'DESCRIPTOR' : _USERSPAGEDATA,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:mirror.UsersPageData)
  })
_sym_db.RegisterMessage(UsersPageData)

GetUserListRequest = _reflection.GeneratedProtocolMessageType('GetUserListRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERLISTREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:mirror.GetUserListRequest)
  })
_sym_db.RegisterMessage(GetUserListRequest)

GetUserListResponse = _reflection.GeneratedProtocolMessageType('GetUserListResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERLISTRESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:mirror.GetUserListResponse)
  })
_sym_db.RegisterMessage(GetUserListResponse)

GetUsersRangeData = _reflection.GeneratedProtocolMessageType('GetUsersRangeData', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSRANGEDATA,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:mirror.GetUsersRangeData)
  })
_sym_db.RegisterMessage(GetUsersRangeData)

GetUsersRangeRequest = _reflection.GeneratedProtocolMessageType('GetUsersRangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSRANGEREQUEST,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:mirror.GetUsersRangeRequest)
  })
_sym_db.RegisterMessage(GetUsersRangeRequest)

GetUsersRangeResponse = _reflection.GeneratedProtocolMessageType('GetUsersRangeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERSRANGERESPONSE,
  '__module__' : 'user_pb2'
  # @@protoc_insertion_point(class_scope:mirror.GetUsersRangeResponse)
  })
_sym_db.RegisterMessage(GetUsersRangeResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
